In [1]:
import pandas as pd
import numpy as np

In [98]:
df_car = pd.read_excel(r"/Users/a.meleshko/Documents/GitHub/DZ/Car Price2.xlsx")

In [100]:
df_car

,Brand,Model,Year,Selling_Price,KM_Driven,Fuel,Seller_Type,Transmission,Owner
0,Maruti,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Hyundai,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
2,Datsun,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
3,Honda,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
4,Hyundai,Hyundai Xcent 1.2 Kappa S,2016,550000,25000,Petrol,Individual,Manual,First Owner
5,Hyundai,Hyundai Creta 1.6 VTVT S,2015,850000,25000,Petrol,Individual,Manual,First Owner
6,Toyota,Toyota Corolla Altis 1.8 VL CVT,2018,1650000,25000,Petrol,Dealer,Automatic,First Owner
7,Hyundai,Hyundai Venue SX Opt Diesel,2019,1195000,5000,Diesel,Dealer,Manual,First Owner
8,Chevrolet,Chevrolet Enjoy TCDi LTZ 7 Seater,2013,390000,33000,Diesel,Individual,Manual,Second Owner
9,Audi,Audi Q5 2.0 TDI,2011,1190000,175900,Diesel,Dealer,Automatic,First Owner
10,Mercedes-Benz,Mercedes-Benz E-Class E 200 CGI Elegance,2010,850000,119000,Petrol,Dealer,Automatic,First Owner
11,Audi,Audi Q7 35 TDI Quattro Premium,2009,1250000,78000,Diesel,Dealer,Automatic,Third Owner
12,Maruti,Maruti Alto LXi,2006,100000,80000,Petrol,Individual,Manual,First Owner
13,Mahindra,Mahindra Jeep CL 500 MDI,1996,250000,35000,Diesel,Individual,Manual,Second Owner
14,Tata,Tata Indica DLS,2005,70000,80000,Diesel,Individual,Manual,First Owner
15,Maruti,Maruti SX4 Zxi BSIII,2008,175000,29173,Petrol,Dealer,Manual,First Owner
16,Maruti,Maruti Zen LX,2004,95000,50000,Petrol,Individual,Manual,First Owner
17,Maruti,Maruti 800 Std,1998,40000,40000,Petrol,Individual,Manual,Fourth & Above Owner
18,Hyundai,Hyundai Santro LP zipPlus,2003,75000,57000,Petrol,Individual,Manual,First Owner
19,Hyundai,Hyundai Santro LE,2002,65000,70000,Petrol,Individual,Manual,First Owner
20,Maruti,Maruti Wagon R LXI,2020,240000,120000,Petrol,Individual,Manual,First Owner
21,Maruti,Maruti 800 AC,2000,60000,40000,Petrol,Individual,Manual,Third Owner
22,Hyundai,Hyundai Santro GLS I - Euro I,1999,50000,120000,Petrol,Individual,Manual,Second Owner
23,Maruti,Maruti 800 AC BSII,2001,43000,100000,Petrol,Individual,Manual,Second Owner
24,Maruti,Maruti Gypsy E MG410W ST,1995,95000,100000,Petrol,Individual,Manual,Second Owner
25,Mahindra,Mahindra Jeep CL 500 MDI,1997,150000,120000,Diesel,Individual,Manual,Third Owner
26,Maruti,Maruti 800 AC BSII,1992,50000,100000,Petrol,Individual,Manual,Fourth & Above Owner

In [136]:
long_data_car = df_car.copy()
long_data_car.set_index(['Year', 'Fuel'], drop = True, inplace = True)

In [138]:
long_data_car

,,Brand,Model,Selling_Price,KM_Driven,Seller_Type,Transmission,Owner
Year,Fuel,,,,,,,
2007,Petrol,Maruti,Maruti 800 AC,60000,70000,Individual,Manual,First Owner
2012,Diesel,Hyundai,Hyundai Verna 1.6 SX,600000,100000,Individual,Manual,First Owner
2017,Petrol,Datsun,Datsun RediGO T Option,250000,46000,Individual,Manual,First Owner
2014,Diesel,Honda,Honda Amaze VX i-DTEC,450000,141000,Individual,Manual,Second Owner
2016,Petrol,Hyundai,Hyundai Xcent 1.2 Kappa S,550000,25000,Individual,Manual,First Owner
2015,Petrol,Hyundai,Hyundai Creta 1.6 VTVT S,850000,25000,Individual,Manual,First Owner
2018,Petrol,Toyota,Toyota Corolla Altis 1.8 VL CVT,1650000,25000,Dealer,Automatic,First Owner
2019,Diesel,Hyundai,Hyundai Venue SX Opt Diesel,1195000,5000,Dealer,Manual,First Owner
2013,Diesel,Chevrolet,Chevrolet Enjoy TCDi LTZ 7 Seater,390000,33000,Individual,Manual,Second Owner
2011,Diesel,Audi,Audi Q5 2.0 TDI,1190000,175900,Dealer,Automatic,First Owner
2010,Petrol,Mercedes-Benz,Mercedes-Benz E-Class E 200 CGI Elegance,850000,119000,Dealer,Automatic,First Owner
2009,Diesel,Audi,Audi Q7 35 TDI Quattro Premium,1250000,78000,Dealer,Automatic,Third Owner
2006,Petrol,Maruti,Maruti Alto LXi,100000,80000,Individual,Manual,First Owner
1996,Diesel,Mahindra,Mahindra Jeep CL 500 MDI,250000,35000,Individual,Manual,Second Owner
2005,Diesel,Tata,Tata Indica DLS,70000,80000,Individual,Manual,First Owner
2008,Petrol,Maruti,Maruti SX4 Zxi BSIII,175000,29173,Dealer,Manual,First Owner
2004,Petrol,Maruti,Maruti Zen LX,95000,50000,Individual,Manual,First Owner
1998,Petrol,Maruti,Maruti 800 Std,40000,40000,Individual,Manual,Fourth & Above Owner
2003,Petrol,Hyundai,Hyundai Santro LP zipPlus,75000,57000,Individual,Manual,First Owner
2002,Petrol,Hyundai,Hyundai Santro LE,65000,70000,Individual,Manual,First Owner
2020,Petrol,Maruti,Maruti Wagon R LXI,240000,120000,Individual,Manual,First Owner
2000,Petrol,Maruti,Maruti 800 AC,60000,40000,Individual,Manual,Third Owner
1999,Petrol,Hyundai,Hyundai Santro GLS I - Euro I,50000,120000,Individual,Manual,Second Owner
2001,Petrol,Maruti,Maruti 800 AC BSII,43000,100000,Individual,Manual,Second Owner
1995,Petrol,Maruti,Maruti Gypsy E MG410W ST,95000,100000,Individual,Manual,Second Owner
1997,Diesel,Mahindra,Mahindra Jeep CL 500 MDI,150000,120000,Individual,Manual,Third Owner
1992,Petrol,Maruti,Maruti 800 AC BSII,50000,100000,Individual,Manual,Fourth & Above Owner

In [140]:
wide_data_car = long_data_car.unstack()

In [142]:
wide_data_car

          Brand                                             Model  \
Fuel     Diesel         Petrol                             Diesel
Year
1992        NaN         Maruti                                NaN
1995        NaN         Maruti                                NaN
1996   Mahindra            NaN           Mahindra Jeep CL 500 MDI
1997   Mahindra            NaN           Mahindra Jeep CL 500 MDI
1998        NaN         Maruti                                NaN
1999        NaN        Hyundai                                NaN
2000        NaN         Maruti                                NaN
2001        NaN         Maruti                                NaN
2002        NaN        Hyundai                                NaN
2003        NaN        Hyundai                                NaN
2004        NaN         Maruti                                NaN
2005       Tata            NaN                    Tata Indica DLS
2006        NaN         Maruti                                NaN
2007        NaN         Maruti                                NaN
2008        NaN         Maruti                                NaN
2009       Audi            NaN     Audi Q7 35 TDI Quattro Premium
2010        NaN  Mercedes-Benz                                NaN
2011       Audi            NaN                    Audi Q5 2.0 TDI
2012    Hyundai            NaN               Hyundai Verna 1.6 SX
2013  Chevrolet            NaN  Chevrolet Enjoy TCDi LTZ 7 Seater
2014      Honda            NaN              Honda Amaze VX i-DTEC
2015        NaN        Hyundai                                NaN
2016        NaN        Hyundai                                NaN
2017        NaN         Datsun                                NaN
2018        NaN         Toyota                                NaN
2019    Hyundai            NaN        Hyundai Venue SX Opt Diesel
2020        NaN         Maruti                                NaN

                                               Selling_Price             \
Fuel                                    Petrol        Diesel     Petrol
Year
1992                        Maruti 800 AC BSII           NaN    50000.0
1995                  Maruti Gypsy E MG410W ST           NaN    95000.0
1996                                       NaN      250000.0        NaN
1997                                       NaN      150000.0        NaN
1998                            Maruti 800 Std           NaN    40000.0
1999             Hyundai Santro GLS I - Euro I           NaN    50000.0
2000                             Maruti 800 AC           NaN    60000.0
2001                        Maruti 800 AC BSII           NaN    43000.0
2002                         Hyundai Santro LE           NaN    65000.0
2003                 Hyundai Santro LP zipPlus           NaN    75000.0
2004                             Maruti Zen LX           NaN    95000.0
2005                                       NaN       70000.0        NaN
2006                           Maruti Alto LXi           NaN   100000.0
2007                             Maruti 800 AC           NaN    60000.0
2008                      Maruti SX4 Zxi BSIII           NaN   175000.0
2009                                       NaN     1250000.0        NaN
2010  Mercedes-Benz E-Class E 200 CGI Elegance           NaN   850000.0
2011                                       NaN     1190000.0        NaN
2012                                       NaN      600000.0        NaN
2013                                       NaN      390000.0        NaN
2014                                       NaN      450000.0        NaN
2015                  Hyundai Creta 1.6 VTVT S           NaN   850000.0
2016                 Hyundai Xcent 1.2 Kappa S           NaN   550000.0
2017                    Datsun RediGO T Option           NaN   250000.0
2018           Toyota Corolla Altis 1.8 VL CVT           NaN  1650000.0
2019                                       NaN     1195000.0        NaN
2020                        Maruti Wagon R LXI           NaN   240000.0

     KM_Driven           Seller_Type             Transmission             \
Fuel    Diesel    Petrol      Diesel      Petrol       Diesel     Petrol
Year
1992       NaN  100000.0         NaN  Individual          NaN     Manual
1995       NaN  100000.0         NaN  Individual          NaN     Manual
1996   35000.0       NaN  Individual         NaN       Manual        NaN
1997  120000.0       NaN  Individual         NaN       Manual        NaN
1998       NaN   40000.0         NaN  Individual          NaN     Manual
1999       NaN  120000.0         NaN  Individual          NaN     Manual
2000       NaN   40000.0         NaN  Individual          NaN     Manual
2001       NaN  100000.0         NaN  Individual          NaN     Manual
2002       NaN   70000.0         NaN  Individual          NaN     Manual
2003       NaN   57000.0         NaN  Individual          NaN     Manual
2004       NaN   50000.0         NaN  Individual          NaN     Manual
2005   80000.0       NaN  Individual         NaN       Manual        NaN
2006       NaN   80000.0         NaN  Individual          NaN     Manual
2007       NaN   70000.0         NaN  Individual          NaN     Manual
2008       NaN   29173.0         NaN      Dealer          NaN     Manual
2009   78000.0       NaN      Dealer         NaN    Automatic        NaN
2010       NaN  119000.0         NaN      Dealer          NaN  Automatic
2011  175900.0       NaN      Dealer         NaN    Automatic        NaN
2012  100000.0       NaN  Individual         NaN       Manual        NaN
2013   33000.0       NaN  Individual         NaN       Manual        NaN
2014  141000.0       NaN  Individual         NaN       Manual        NaN
2015       NaN   25000.0         NaN  Individual          NaN     Manual
2016       NaN   25000.0         NaN  Individual          NaN     Manual
2017       NaN   46000.0         NaN  Individual          NaN     Manual
2018       NaN   25000.0         NaN      Dealer          NaN  Automatic
2019    5000.0       NaN      Dealer         NaN       Manual        NaN
2020       NaN  120000.0         NaN  Individual          NaN     Manual

             Owner
Fuel        Diesel                Petrol
Year
1992           NaN  Fourth & Above Owner
1995           NaN          Second Owner
1996  Second Owner                   NaN
1997   Third Owner                   NaN
1998           NaN  Fourth & Above Owner
1999           NaN          Second Owner
2000           NaN           Third Owner
2001           NaN          Second Owner
2002           NaN           First Owner
2003           NaN           First Owner
2004           NaN           First Owner
2005   First Owner                   NaN
2006           NaN           First Owner
2007           NaN           First Owner
2008           NaN           First Owner
2009   Third Owner                   NaN
2010           NaN           First Owner
2011   First Owner                   NaN
2012   First Owner                   NaN
2013  Second Owner                   NaN
2014  Second Owner                   NaN
2015           NaN           First Owner
2016           NaN           First Owner
2017           NaN           First Owner
2018           NaN           First Owner
2019   First Owner                   NaN
2020           NaN           First Owner

In [150]:
df_car.pivot(index = 'Year', columns = 'Brand', values = 'Selling_Price')

Brand,Audi,Chevrolet,Datsun,Honda,Hyundai,Mahindra,Maruti,Mercedes-Benz,Tata,Toyota
Year,,,,,,,,,,
1992,NaN,NaN,NaN,NaN,NaN,NaN,50000.0,NaN,NaN,NaN
1995,NaN,NaN,NaN,NaN,NaN,NaN,95000.0,NaN,NaN,NaN
1996,NaN,NaN,NaN,NaN,NaN,250000.0,NaN,NaN,NaN,NaN
1997,NaN,NaN,NaN,NaN,NaN,150000.0,NaN,NaN,NaN,NaN
1998,NaN,NaN,NaN,NaN,NaN,NaN,40000.0,NaN,NaN,NaN
1999,NaN,NaN,NaN,NaN,50000.0,NaN,NaN,NaN,NaN,NaN
2000,NaN,NaN,NaN,NaN,NaN,NaN,60000.0,NaN,NaN,NaN
2001,NaN,NaN,NaN,NaN,NaN,NaN,43000.0,NaN,NaN,NaN
2002,NaN,NaN,NaN,NaN,65000.0,NaN,NaN,NaN,NaN,NaN
2003,NaN,NaN,NaN,NaN,75000.0,NaN,NaN,NaN,NaN,NaN
2004,NaN,NaN,NaN,NaN,NaN,NaN,95000.0,NaN,NaN,NaN
2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70000.0,NaN
2006,NaN,NaN,NaN,NaN,NaN,NaN,100000.0,NaN,NaN,NaN
2007,NaN,NaN,NaN,NaN,NaN,NaN,60000.0,NaN,NaN,NaN
2008,NaN,NaN,NaN,NaN,NaN,NaN,175000.0,NaN,NaN,NaN
2009,1250000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,850000.0,NaN,NaN
2011,1190000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012,NaN,NaN,NaN,NaN,600000.0,NaN,NaN,NaN,NaN,NaN
2013,NaN,390000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014,NaN,NaN,NaN,450000.0,NaN,NaN,NaN,NaN,NaN,NaN
2015,NaN,NaN,NaN,NaN,850000.0,NaN,NaN,NaN,NaN,NaN
2016,NaN,NaN,NaN,NaN,550000.0,NaN,NaN,NaN,NaN,NaN
2017,NaN,NaN,250000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1650000.0
2019,NaN,NaN,NaN,NaN,1195000.0,NaN,NaN,NaN,NaN,NaN
2020,NaN,NaN,NaN,NaN,NaN,NaN,240000.0,NaN,NaN,NaN

In [131]:
wide_data_car = long_data_car.unstack()
wide_data_car.columns = ['Petrol', 'Diesel']
wide_data_car

ValueError: Length mismatch: Expected axis has 14 elements, new values have 2 elements